spring:
  flyway:
    locations: classpath:/db/testdata
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: gfd
    password: 111
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
jwt:
  secret: hbavouefvouaeffvouebviuo2332432$l4j23our34ouht08sljccdflefb